---
title: "Description of the attitude survey questions"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
```

#####1. mental health consequence: Do employees think that discussing a mental health issue with employer would have negative consequences? 
 - "1" for no negative consequences at all 
 - "0" for having negative consequencese for sure
 
#####2. physical health consequence: Do employees think that discussing a physical health issue with employer would have negative consequences?
 - "1" for no negative consequences at all
 - "0" for having negative consequencese for sure

#####3. Talk with coworkers: Would employee be willing to discuss a mental health issue with coworkers? 
 - "1" for willing to talk about mental health issues with coworkers
 - "0" for not willing to talk about mental health issues with coworkers

#####4. Talk with supervisor: Would employee be willing to discuss a mental health issue with direct supervisor(s)?
 - "1" for willing to talk about mental health issues with supervisor
 - "0" for not willing to talk about mental health issues with supervisor
 
#####5. Discuss Mental Health at Interview: Would employee bring up a mental health issue with a potential employer in an interview?
- "1" for yes
- "0" for no

#####6. Discuss Physical Health at Interview:Would employee bring up a physical health issue with a potential employer in an interview?
- "1" for yes
- "0" for no

#####7. Mental vs Physical Health: Do you feel that employer takes mental health as seriously as physical health?
- "1" for yes
- "0" for no

#####8. Observed consequences:Has employee heard of or observed negative consequences for coworkers with mental health conditions in your workplace?
- "1" for no
- "0" for yes